fix docker workflow

diff --git a/.github/workflows/dotnet-docker.yml b/.github/workflows/dotnet-docker.yml
--- a/.github/workflows/dotnet-docker.yml
+++ b/.github/workflows/dotnet-docker.yml
@@ -1,56 +1,107 @@
 
 
 
-name: .NET Tests and Docker Build
+# name: .NET Tests and Docker Build
+
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+#     branches:
+#       - main
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v3
+
+#     - name: Set up .NET
+#       uses: actions/setup-dotnet@v3
+#       with:
+#         dotnet-version: '8'
+
+#     - name: Install dependencies
+#       run: dotnet restore
+
+#     - name: Build
+#       run: dotnet build --no-restore
+
+#     - name: Run tests
+#       run: dotnet test --no-build --verbosity normal
+
+#     - name: Publish test results
+#       if: success() || failure()
+#       uses: actions/upload-artifact@v3
+#       with:
+#         name: test-results
+#         path: '**/TestResults/*.xml'
+
+#     - name: Build Docker image
+#       run: |
+#         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blog_dotnet:latest .
+
+#     - name: Log in to Docker Hub
+#       uses: docker/login-action@v2
+#       with:
+#         username: ${{ secrets.DOCKERHUB_USERNAME }}
+#         password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+#     - name: Push Docker image to Docker Hub
+#       run: |
+#         docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog_dotnet:latest
+
+# This workflow uses actions that are not certified by GitHub.
+# They are provided by a third-party and are governed by
+# separate terms of service, privacy policy, and support
+# documentation.
+
+# GitHub recommends pinning actions to a commit SHA.
+# To get a newer version, you will need to update the SHA.
+# You can also reference a tag or branch, but the action may change without warning.
+
+name: Publish Docker image
 
 on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+  release:
+    types: [published]
 
 jobs:
-  build:
+  push_to_registry:
+    name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
-
+    permissions:
+      packages: write
+      contents: read
+      attestations: write
+      id-token: write
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Check out the repo
+        uses: actions/checkout@v4
 
-    - name: Set up .NET
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: '8'
+      - name: Log in to Docker Hub
+        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    - name: Install dependencies
-      run: dotnet restore
+      - name: Extract metadata (tags, labels) for Docker
+        id: meta
+        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
+        with:
+          images: my-docker-hub-namespace/my-docker-hub-repository
 
-    - name: Build
-      run: dotnet build --no-restore
-
-    - name: Run tests
-      run: dotnet test --no-build --verbosity normal
-
-    - name: Publish test results
-      if: success() || failure()
-      uses: actions/upload-artifact@v3
-      with:
-        name: test-results
-        path: '**/TestResults/*.xml'
-
-    - name: Build Docker image
-      run: |
-        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blog_dotnet:latest .
-
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-    - name: Push Docker image to Docker Hub
-      run: |
-        docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog_dotnet:latest
+      - name: Build and push Docker image
+        id: push
+        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          tags: latest
+          # tags: ${{ steps.meta.outputs.tags }}
+          # labels: ${{ steps.meta.outputs.labels }}
 
